PM: OMAP: Fix build with CONFIG_OMAP_PM_NONE set
Removes undefined symbol link errors when CONFIG_OMAP_PM is set.
The required symbols are defined in common.c and omap-pm.h
Dummy variables mpu_oops, dsp_oops and l3_oops have to be defined
because they are used in a number of places

It fixes the following link errors

arch/arm/mach-omap2/built-in.o: In function `omap3_round_to_table_rate':
arch/arm/mach-omap2/clock34xx.c:956: undefined reference to `mpu_opps'
arch/arm/mach-omap2/clock34xx.c:956: undefined reference to `dsp_opps'
arch/arm/mach-omap2/clock34xx.c:956: undefined reference to `l3_opps'
arch/arm/mach-omap2/built-in.o: In function `omap2_init_common_hw':
arch/arm/mach-omap2/io.c:241: undefined reference to
`omap_pm_if_early_init'
arch/arm/mach-omap2/io.c:246: undefined reference to `omap_pm_if_init'
make: *** [.tmp_vmlinux1] Error 1

Signed-off-by: Roger Quadros <ext-roger.quadros@nokia.com>